#!/bin/bash

cpu=`cat /proc/cpuinfo | grep "model name" | uniq | sed -e 's/model name.*: //'`
echo Procesor: $cpu

memKb=`cat /proc/meminfo  | grep MemTotal | sed -e 's/MemTotal: *\([0-9]*\).*kB/\1/'`
freeMemKb=`cat /proc/meminfo  | grep MemFree | sed -e 's/MemFree: *\([0-9]*\).*kB/\1/'`
mem=`echo $memKb/1024/1024 | bc`
freeMem=`echo $freeMemKb/1024/1024 | bc`
echo Memory: $freeMem / $mem GB

disk=`df -h / | grep /dev | cut -d " " -f 20`
echo Free disk space on root: $disk

system=`uname`
version=`uname -r`
echo System: $system $version

